---
- name: Update packages
  apt:
    state: latest
    update_cache: yes
    upgrade: safe
    autoremove: yes
    autoclean: yes
    force_apt_get: yes

- name: Install base packages
  apt:
    state: present
    name:
      - bzip2
      - unzip
      - git
      - wget
      - curl
      - vim
      - python-pip
      - gpg
      - collectd
      - rsyslog
    install_recommends: yes
    force_apt_get: yes

- name: Install base python modules
  pip:
    state: present
    name:
      - testinfra

- name: Create group account for base operation
  group:
    state: present
    name: "{{ base_group_name }}"
    gid: "{{ base_group_gid }}"
  tags: ["base-group"]

- name: Create extra group accounts for base operation
  group:
    state: present
    name: "{{ extra_group.name }}"
    gid: "{{ extra_group.gid }}"
  loop: "{{ base_user_groups }}"
  loop_control:
    loop_var: extra_group
  tags: ["extra-groups"]

- name: Create user account for base operation
  user:
    state: present
    name: "{{ base_user_name }}"
    uid: "{{ base_user_uid }}"
    group: "{{ base_group_name }}"
    system: no
    home: "{{ base_user_home }}"
    create_home: no
    shell: "{{ base_user_shell }}"
    groups: "{{ base_user_groups | map(attribute='name') | list | join(',') }}"
  tags: ["base-user"]

- name: Ensure base directory structure is in place
  file:
    state: directory
    path: "{{ base_dir }}"
    owner: "{{ base_dir_owner }}"
    group: "{{ base_dir_group }}"
    mode: "{{ base_dir_mode }}"
  loop:
    - "{{ base_source_dir }}"
    - "{{ base_download_dir }}"
    - "{{ base_bin_dir }}"
  loop_control:
    loop_var: base_dir

- name: Set proper sudo permissions
  lineinfile:
    state: present
    line: ubuntu ALL=(ALL:ALL) NOPASSWD:ALL
    path: /etc/sudoers.d/90-cloud-init-users
    regexp: ^ubuntu

- name: Install cloud-init config
  copy:
    src: 10_partition_vda.cfg
    dest: /etc/cloud/cloud.cfg.d/10_partition_vda.cfg
    owner: root
    group: root
    mode: "0644"

- name: Install boot-time partitioning script
  copy:
    src: partition-vda.sh
    dest: /usr/local/sbin/partition-vda.sh
    owner: root
    group: root
    mode: "0700"
