---
- name: Ensure /etc/exports exists
  become: yes
  file:
    path: /etc/exports
    state: touch
    owner: root
    group: root
    mode: "0644"

- name: Ensure NFS shared directory exists
  file:
    path: "{{ nfs_share_path }}"
    state: directory
    owner: "{{ nfs_share_owner }}"
    group: "{{ nfs_share_group }}"
    mode: "{{ nfs_share_mode }}"

- name: Ensure NFS shared directory is exported
  become: yes
  lineinfile:
    path: /etc/exports
    state: present
    regexp: "^{{ nfs_share_path }}"
    # Security groups will take care of the connection restrictions
    line: "{{ nfs_share_path }} *(rw,sync,no_root_squash,no_subtree_check)"

- name: Install NFS packages
  become: yes
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present
    update_cache: yes
    force_apt_get: yes
