---
- name: Install NFS common package
  apt:
    state: present
    name:
      - nfs-common
    install_recommends: yes
    force_apt_get: yes

- name: Wait for master NFS Server to come up
  wait_for:
    state: started
    host: "{{ nfs_server }}"
    port: 111
    delay: 10
    sleep: 5

- name: Mount Spark local directory
  mount:
    path: "{{ nfs_mount_point }}"
    state: mounted
    src: "{{ nfs_server }}:{{ nfs_share_path }}"
    boot: no
    fstype: nfs4
