---
- name: Set hadoop_version fact
  set_fact:
    hadoop_version: "{{ hadoop_version_major }}.{{ hadoop_version_minor }}.{{ hadoop_version_patch }}"

- name: Set hadoop_home fact
  set_fact:
    hadoop_home: "{{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}"

- name: Ensure Java is installed
  apt:
    state: present
    name:
      - default-jdk

- name: Create group account for Hadoop
  group:
    state: present
    name: "{{ hadoop_group_name }}"
    gid: "{{ hadoop_group_gid }}"
  tags: ["hadoop-group"]

- name: Create user account for Hadoop
  user:
    state: present
    name: "{{ hadoop_user_name }}"
    uid: "{{ hadoop_user_uid }}"
    group: "{{ hadoop_group_name }}"
    system: no
    home: "{{ hadoop_home }}"
    shell: "{{ hadoop_user_shell }}"
    groups: "{{ hadoop_user_groups | join(',') }}"
  tags: ["hadoop-user"]

- name: Ensure Hadoop download and install directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    follow: true
  with_items:
    - "{{ hadoop_download_dir }}"
    - "{{ hadoop_install_dir }}"

- name: Download Hadoop distribution
  rcet_url:
    url: "{{ hadoop_mirror }}/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}-src.tar.gz"
    dest: "{{ hadoop_download_dir }}/hadoop-{{ hadoop_version }}-src.tar.gz"

# FIXME: This should really be implemented https://hadoop.apache.org/releases.html
#
# - name: Verify downloaded Hadoop distribution
#   command: /bin/true

- name: Extract Hadoop distribution
  unarchive:
    src: "{{ hadoop_download_dir }}/hadoop-{{ hadoop_version }}-src.tar.gz"
    dest: "{{ hadoop_install_dir }}"
    copy: no
    owner: "{{ hadoop_user_name }}"
    group: "{{ hadoop_group_name }}"
    creates: "{{ hadoop_home }}"

- name: Cleanup downloaded Hadoop distribution
  file:
    state: absent
    name: "{{ hadoop_download_dir }}/hadoop-{{ hadoop_version }}-src.tar.gz"

- name: Create symlink to Hadoop versioned installation directory
  file:
    state: link
    path: "{{ hadoop_install_dir }}/hadoop"
    src: "{{ hadoop_home }}"
