---
- name: Set hadoop_home fact
  set_fact:
    hadoop_home: "{{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}"

- name: Create group account for Hadoop
  group:
    state: present
    name: "{{ hadoop_group_name }}"
    gid: "{{ hadoop_group_gid }}"
  tags: ["hadoop-group"]

- name: Create user account for Hadoop
  user:
    state: present
    name: "{{ hadoop_user_name }}"
    uid: "{{ hadoop_user_uid }}"
    group: "{{ hadoop_group_name }}"
    system: no
    home: "{{ hadoop_home }}"
    create_home: no
    shell: "{{ hadoop_user_shell }}"
    groups: "{{ hadoop_user_groups | join(',') }}"
  tags: ["hadoop-user"]

- name: Ensure Hadoop download and install directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0775
    follow: true
  with_items:
    - "{{ hadoop_download_dir }}"
    - "{{ hadoop_install_dir }}"

- name: Download Hadoop distribution
  get_url:
    url: "{{ hadoop_mirror }}/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ hadoop_download_dir }}/hadoop-{{ hadoop_version }}.tar.gz"

# TODO: This should really be implemented https://hadoop.apache.org/releases.html
#
# - name: Verify downloaded Hadoop distribution
#   command: /bin/true

- name: Extract Hadoop distribution
  unarchive:
    src: "{{ hadoop_download_dir }}/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ hadoop_install_dir }}"
    copy: no
    owner: "{{ hadoop_install_owner }}"
    group: "{{ hadoop_install_group }}"
    mode: "u+rw,go+r"
    list_files: yes

- name: Ensure Hadoop runtime directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    owner: "{{ hadoop_user_name }}"
    group: "{{ hadoop_group_name }}"
  with_items:
    - "{{ hadoop_home }}/run"
    - "{{ hadoop_home }}/log"
    - "{{ hadoop_home }}/tmp"

- name: Create symlink to Hadoop versioned installation directory
  file:
    state: link
    path: "{{ hadoop_install_dir }}/hadoop"
    src: "{{ hadoop_home }}"

- name: Set Hadoop profile variables
  template:
    src: profile.sh.tpl
    dest: /etc/profile.d/hadoop.sh
