---
- name: Ensure Java and Scala are installed
  apt:
    state: present
    name:
      - scala
      - default-jdk

- name: Ensure Spark download and install directories exist
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    follow: true
  with_items:
    - "{{ spark_download_dir }}"
    - "{{ spark_install_dir }}"

- name: Download Spark distribution
  get_url:
    url: "{{ spark_mirror }}/spark-{{ spark_version }}.tgz"
    dest: "{{ spark_download_dir }}/spark-{{ spark_version }}.tgz"

# FIXME: This should really be implemented
#        https://www.apache.org/dyn/closer.lua/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz
#
# - name: Verify downloaded Spark distribution
#   command: /bin/true

- name: Set spark_home fact
  set_fact:
    spark_home: "{{ spark_install_dir }}/spark-{{ spark_version }}"

- name: Extract Spark distribution
  unarchive:
    src: "{{ spark_download_dir }}/spark-{{ spark_version }}.tgz"
    dest: "{{ spark_install_dir }}"
    copy: no
    creates: "{{ spark_home }}"

- name: Cleanup downloaded Spark distribution
  file:
    state: absent
    name: "{{ spark_download_dir }}/spark-{{ spark_version }}.tgz"

- name: Create service account for Spark
  user:
    state: present
    name: "{{ spark_user_username }}"
    system: yes
    home: "{{ spark_home }}"
    shell: "{{ spark_user_shell }}"
    groups: "{{ spark_user_groups | join(',') }}"
  tags: ["spark-user"]

- name: Ensure Spark configuration directory exists
  file:
    state: directory
    path: "{{ spark_home }}/conf"
    owner: "{{ spark_user_username }}"
    group: "{{ spark_user_username }}"
  tags: ["config"]

- name: Ensure Spark log, run, temp and work directories exist
  file:
    state: directory
    path: "{{ spark_home }}/{{ item }}"
    owner: "{{ spark_user_username }}"
    group: "{{ spark_user_username }}"
    mode: 0775
  with_items:
    - log
    - run
    - temp
    - work

- name: Ensure Spark local directories exist
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ spark_user_username }}"
    group: "{{ spark_user_username }}"
    mode: "{{ spark_local_dir_mode }}"
  when: item != "/tmp"
  with_items: "{{ spark_local_dirs }}"
  tags: ["spark-local-dirs"]

- name: Configure Spark environment
  template:
    src: spark-env.sh.j2
    dest: "{{ spark_home }}/conf/spark-env.sh"
  tags: ["config"]

- name: Configure Spark defaults config file
  template:
    src: spark-defaults.conf.j2
    dest: "{{ spark_home }}/conf/spark-defaults.conf"
  tags: ["config"]

- name: Deploy Spark log4j properties
  template:
    src: log4j.properties.j2
    dest: "{{ spark_home }}/conf/log4j.properties"
    owner: "{{ spark_user_username }}"
    group: "{{ spark_user_username }}"
