---
- name: Format hadoop-namenode
  become: yes
  become_user: "{{ hadoop_user_name }}"
  command: "echo 'Y' | {{ hadoop_home }}/bin/hdfs namenode -format"

- name: Enable and start hadoop-datanode service
  become: yes
  service:
    name: hadoop-datanode
    enabled: yes
    state: started

- name: Enable and start hadoop-namenode service
  become: yes
  service:
    name: hadoop-namenode
    enabled: yes
    state: started
