---
- name: Format hadoop-namenode
  become: yes
  become_user: "{{ hadoop_user_name }}"
  command: "{{ hadoop_home }}/bin/hdfs namenode -format -nonInteractive"
  run_once: yes
  environment:
    JAVA_HOME: "{{ java_home }}"

- name: Enable and start hadoop-namenode service
  become: yes
  service:
    name: hadoop-namenode
    enabled: yes
    state: started
