---
# tasks file for common
- name: install base packages
  apt:
    state: present
    name:
      - git
      - wget
      - curl
      - vim
      - python-pip
- name: install testinfra python module
  pip:
    state: present
    name:
      - testinfra
