---
- name: Ensure spark-master address is set in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ spark_master_private_address | default('127.0.0.1', true) }} spark-master"

- name: Configure Collectd
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
  notify:
    - Restart Collectd

- name: Configure RsyslogD
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify:
    - Restart RsyslogD

- name: Create LUKS keyfile
  copy:
    dest: password
    content: "{{ password }}"
    mode: "0600"

- name: Ensure LVM volume group is created on extra volumes
  lvg:
    state: present
    force: no
    pesize: "4"
    vg: "{{ volume['vg'] }}"
    pvs: "{{ volume['device'] }}"
  loop: "{{ volumes }}"
  loop_control:
    loop_var: volume

- name: Ensure LVM logical volume is created on extra volumes
  lvol:
    vg: "{{ volume['vg'] }}"
    lv: "{{ volume['lv'] }}"
    size: +100%FREE
    resizefs: yes
  loop: "{{ volumes }}"
  loop_control:
    loop_var: volume

- name: Ensure LUKS container is configured on extra volumes
  luks_device:
    state: "{{ volume['luks_state'] }}"
    device: "/dev/mapper/{{ volume['vg'] }}-{{ volume['lv'] }}"
    name: "{{ volume['luks_name'] }}"
    keyfile: "password"
  loop: "{{ volumes }}"
  loop_control:
    loop_var: volume

- name: Ensure that a filesystem exists on extra volumes
  filesystem:
    dev: "{{ volume['filesystem_dev'] }}"
    force: yes
    type: "{{ volume['filesystem_type'] }}"
  loop: "{{ volumes }}"
  loop_control:
    loop_var: volume

- name: Mount extra volumes
  mount:
    state: mounted
    src: "{{ volume['filesystem_dev'] }}"
    fstype: "{{ volume['filesystem_type'] }}"
    path: "{{ volume['mount_path'] }}"
  loop: "{{ volumes }}"
  loop_control:
    loop_var: volume
