---
galaxy_info:
  author: Ahuja, Piyush
  description: Installs and prepare docker swarm manager
  company: Wellcome Sanger Institute, Genome Research Limited

  issue_tracker_url: https://github.com/wtsi-hgi/hgi-cloud/issues

  license: BSD

  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - 18.04

  galaxy_tags: []
dependencies:
  - docker-base
