
version: '3.5'

# Compose has commands for managing the whole lifecycle of your application:

# Start, stop, and rebuild services
# View the status of running services
# Stream the log output of running services
# Run a one-off command on a service

services:
  backend:
    image: mercury/openstack_report_backend:prod
    ports: 
      - "3000:3000" 
    secrets:
      - source: backend_secret
        target: /app/hgi-openrc.sh
    networks: [app]

  frontend:
    image: mercury/openstack_report_frontend:prod    
    depends_on: 
      - backend
    command: "npm run serve -- --mode production"
    networks: [app]
  
  weaver:
    image: mercury/hgi-weaver:1.1.3 
    ports:
      - "3838:3838"
    secrets:
      - source: weaver_secret      
        target: /srv/shiny-server/weaver/config.yml
      - source: weaver_secret      
        target: /srv/shiny-server/spaceman/config.yml
    networks: [app]

  login-page:
    image: mercury/auth-login-page
    ports:
      - "9000:9000"
    networks: [app]

  nginx-ldap-auth-daemon:
    image: mercury/nginx-ldap-auth-daemon:test 
    ports:
      - "8888:8888"
    networks: [app]

  nginx:
    image: nginx 
    ports: 
      - "80:8080"
    depends_on:
      - frontend
      - backend
      - weaver
      - login-page
      - nginx-ldap-auth-daemon
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf 
    networks: [app]

secrets:
   backend_secret:
      file: hgi-openrc.sh
   weaver_secret:
      file: config.yml    
  
configs:
   nginx_config:
      file: nginx.conf

networks:
  app:
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.1/24
