---
- name: Ensure deprecated Docker packages are absent
  apt:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    force_apt_get: true

- name: Add Docker APT repository key
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    state: present
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb['codename'] }} stable"

- name: Create Docker configuration directory
  file:
    state: directory
    path: /etc/docker

- name: Pre-configure Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Ensure Docker is installed
  apt:
    state: present
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io
    install_recommends: true
    force_apt_get: true

- name: Ensure python3 docker module is istalled
  pip:
    name: docker
    state: present
    executable: /usr/bin/pip3

- name: Ensure base user belongs to the docker gorup
  user:
    name: "{{ base_user_name }}"
    groups:
      - docker
