---
- name: Ensure logs directory exists
  file:
    path: "{{ hail_home }}/log"
    state: directory
    owner: "{{ hail_install_owner }}"
    group: "{{ hail_install_group }}"
    mode: "{{ hail_install_mode }}"

- name: Install Hail in Anaconda3
  pip:
    state: present
    name:
      - "hail=={{ hail_version }}"
      - parsimonious==0.8.0
    executable: "{{ anaconda_install_dir }}/anaconda3/bin/pip"
  become: yes
  become_user: "{{ hail_install_owner }}"
