---
- name: Ensure logs directory exists
  file:
    path: "{{ hail_home }}/log"
    state: directory
    owner: "{{ hail_install_owner }}"
    group: "{{ hail_install_group }}"
    mode: "{{ hail_install_mode }}"

- name: Install Hail in Anaconda3
  pip:
    state: present
    name:
      - "hail=={{ hail_version }}"
      - parsimonious==0.8.0
    executable: "{{ anaconda_install_dir }}/anaconda3/bin/pip"
  become: yes
  become_user: "{{ hail_install_owner }}"

- name: Create extra jars path
  file:
    state: directory
    path: "{{ hail_install_dir }}/jars"
    mode: "{{ hail_install_mode }}"
    owner: "{{ hail_install_owner }}"
    group: "{{ hail_install_group }}"

- name: Install custom jars list
  get_url:
    url: "{{ jar.url }}"
    dest: "{{ hail_install_dir }}/jars/{{ jar.filename }}"
  loop: "{{ hail_extra_jars }}"
  loop_control:
    loop_var: jar

- name: Install custom python modules
  pip:
    state: present
    name: "{{ hail_extra_pip }}"
    executable: "{{ anaconda_install_dir }}/anaconda3/bin/pip"
  become: yes
  become_user: "{{ hail_install_owner }}"

- name: Install sustom system packages
  apt:
    state: present
    name: "{{ hail_extra_apt }}"
    install_recommends: yes
    force_apt_get: yes
