---
# tasks file for docker-swarm-worker
- name: Open up docker socket
  file:
    state: file
    path: /var/run/docker.sock
    mode: "0666"

- name: Ensure docker manager address is set in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ docker_manager_private_address | default('127.0.0.1', true) }} docker-manager"

- name: Create a tombstone container that prevents the default docker_gwbridge network to use 172.17.** subnet
# https://stackoverflow.com/questions/50514275/docker-bridge-conflicts-with-host-network
  docker_network:
    name: tombstone
    state: present
    force: yes
    ipam_config:
     - subnet: 172.17.253.0/30
- name: Create a second tombstone container that prevents the default docker_gwbridge network to use 172.18.** subnet
# https://stackoverflow.com/questions/50514275/docker-bridge-conflicts-with-host-network
  docker_network:
    name: tombstone-two
    state: present
    force: yes
    ipam_config:
      - subnet: 172.18.253.0/30
- name: Wait for docker swarm manager to come up.
  wait_for:
    state: started
    host: docker-manager
    port: 90
    delay: 10
    sleep: 5
- name: Get token
  uri:
    url: "http://{{ docker_manager_private_address }}:90"
    return_content: yes
  register: token
- name: join swarm
  docker_swarm:
    state: join
    advertise_addr: docker-manager
    join_token: "{{ token.content }}"
    remote_addrs: "{{ docker_manager_private_address }}:2377"

