---
- name: Set hadoop_home fact
  set_fact:

- name: Ensure group account for Hadoop exist
  group:
    state: present
    name: "{{ hadoop_group_name }}"
#    gid: "{{ hadoop_group_gid }}"
#  tags: ["hadoop-group"]

- name: Ensure user account for Hadoop exist
  user:
    state: present
    name: "{{ hadoop_user_name }}"
#     uid: "{{ hadoop_user_uid }}"
#     group: "{{ hadoop_group_name }}"
#     system: no
#     home: "{{ hadoop_home }}"
#     create_home: no
#     shell: "{{ hadoop_user_shell }}"
#     groups: "{{ hadoop_user_groups | join(',') }}"
#   tags: ["hadoop-user"]

- name: Ensure Hadoop download and install directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ hadoop_download_dir }}"
    - "{{ hadoop_install_dir }}"

- name: Download Hadoop distribution
  get_url:
    url: "{{ hadoop_mirror }}/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ hadoop_download_dir }}/hadoop-{{ hadoop_version }}.tar.gz"

# TODO: This should really be implemented https://hadoop.apache.org/releases.html
#
# - name: Verify downloaded Hadoop distribution
#   command: /bin/true

- name: Extract Hadoop distribution
  unarchive:
    src: "{{ hadoop_download_dir }}/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "{{ hadoop_install_dir }}"
    copy: no
    owner: "{{ hadoop_install_owner }}"
    group: "{{ hadoop_install_group }}"
    mode: "{{ hadoop_install_mode }}"
    list_files: yes
    creates: "{{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}/README.txt"

- name: Ensure Hadoop runtime directories exist
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ hadoop_install_owner }}"
    group: "{{ hadoop_install_group }}"
    mode: "{{ hadoop_install_mode }}"
  with_items:
    - "{{ hadoop_pid_dir }}"
    - "{{ hadoop_log_dir }}"
    - "{{ hadoop_tmp_dir }}"

- name: Create symlink to Hadoop versioned installation directory
  file:
    state: link
    path: "{{ hadoop_install_dir }}/hadoop"
    src: "{{ hadoop_home }}"

- name: Configure system-wide environment variables
  template:
    src: profile.sh.j2
    dest: /etc/profile.d/20-hadoop.sh
