---
- name: Restart Collectd
  service:
    name: collectd
    state: restarted

- name: Restart RsyslogD
  service:
    name: rsyslog
    state: restarted

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
