---
- name: Ensure workstation's packages are installed
  apt:
    state: present
    name:
      - python3
      - python3-dev
      - virtualenv
    install_recommends: true
    force_apt_get: true
