---
- name: Wait for master NFS Server to come up
  wait_for:
    state: started
    host: pet-master
    port: 111
    delay: 10
    sleep: 5

- name: Mount Spark local directory
  mount:
    path: "{{ spark_temp_dir }}"
    state: mounted
    src: "pet-master:{{ spark_home }}/local"
    boot: no
    fstype: nfs4

- name: Enable and start spark-slave service
  become: yes
  service:
    name: spark-slave
    enabled: yes
    state: started
