---
- name: Creates Hail's Jupyter Notebook directories
  file:
    path: "{{ jupyter_dir }}"
    state: directory
    owner: "{{ jupyter_install_owner }}"
    group: "{{ jupyter_install_group }}"
  loop:
    - "{{ jupyter_install_dir }}/jupyter"
    - "{{ jupyter_install_dir }}/jupyter/config"
    - "{{ jupyter_install_dir }}/jupyter/data"
  loop_control:
    loop_var: jupyter_dir

- name: Install Hail's Jupyter Notebook service
  template:
    src: jupyter-notebook.service.j2
    dest: /etc/systemd/system/jupyter-notebook.service

- name: Install Hail's Jupyter Notebook bash profile
  template:
    src: profile.sh.j2
    dest: /etc/profile.d/50-jupyeter.sh
    mode: 0644

- name: Install Hail's Jupyter Notebook configuration file
  become: yes
  template:
    src: jupyter-config-service.py.j2
    dest: "{{ jupyter_install_dir }}/jupyter/config/service.py"
    owner: "{{ jupyter_install_owner }}"
    group: "{{ jupyter_install_group }}"
    mode: 0600

- name: Enable and start Hail's Jupyter Notebook service
  become: yes
  service:
    name: jupyter-notebook
    enabled: yes
    state: started
