---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - ../../../../vars/eta.yml
    - ../../../../vars/eta/hgi.yml
    - ../../../../vars/eta/hgi/dev.yml
    - ../../../../molecule/default/metadata.yml
  tasks:
    - name: Set spark_master_private_address fact
      set_fact:
        spark_master_private_address: "127.0.0.1"
        spark_master_external_address: "127.0.0.1"

    - name: Run platform's role
      include_role:
        name: "{{ role }}"
      loop:
        - hail-master
        - hail-slave
      loop_control:
        loop_var: role
