---
- name: Download Anaconda3 installer
  get_url:
    url: "{{ anaconda_mirror }}/Anaconda3-{{ anaconda_distribution }}.sh"
    dest: "{{ anaconda_download_dir }}"

- name: Install Anaconda3
  command: |
    /bin/bash {{ anaconda_download_dir }}/Anaconda3-{{ anaconda_distribution }}.sh \
      -p {{ anaconda_install_dir }}/anaconda3 -b -s
  args:
    creates: "{{ anaconda_install_dir }}/anaconda3/bin/conda"

- name: Fix ownership and permissions on anaconda installation
  file:
    state: directory
    path: "{{ anaconda_install_dir }}/anaconda3"
    recurse: yes
    owner: "{{ anaconda_install_owner }}"
    group: "{{ anaconda_install_group }}"
    mode: "{{ anaconda_install_mode }}"

- name: Update anaconda packages
  become: yes
  become_user: "{{ anaconda_install_owner }}"
  command: "{{ anaconda_install_dir }}/anaconda3/bin/conda update --yes --all"

- name: Remove Anaconda3's curl
  become: yes
  become_user: "{{ anaconda_install_owner }}"
  command: "{{ anaconda_install_dir }}/anaconda3/bin/conda remove --yes curl"
  ignore_errors: yes

- name: Install extra Anaconda3's modules
  become: yes
  become_user: "{{ anaconda_install_owner }}"
  command: "{{ anaconda_install_dir }}/anaconda3/bin/conda install --yes {{ anaconda_extra_modules | join(' ') }}"
  when: anaconda_extra_modules != []

- name: Set up system-wide environment variables
  template:
    src: profile.sh.tpl
    dest: /etc/profile.d/anaconda3.sh
    mode: 0644
