---
spark_version_major: 2
spark_version_minor: 4
spark_version_patch: 1
spark_mirror: "https://archive.apache.org/dist/spark/"

spark_group_name: "spark"
spark_group_gid: 10002

spark_user_name: "spark"
spark_user_uid: 10002
spark_user_groups: []
spark_user_shell: "/bin/false"

spark_source_dir: "/opt/sanger.ac.uk/src"
spark_download_dir: "/opt/sanger.ac.uk/download"
spark_install_dir: "/opt/sanger.ac.uk"

spark_local_dirs: []
spark_local_dir_mode: "1777"

spark_env_extras: {}
spark_defaults_extras: {}

# Logger levels set to the official defaults
# Ref: https://github.com/apache/spark/blob/master/conf/log4j.properties.template
spark_log4j_extras:
  - name: log4j.logger.org.apache.spark.repl.Main
    value: WARN
  - name: log4j.logger.org.spark_project.jetty
    value: WARN
  - name: log4j.logger.org.spark_project.jetty.util.component.AbstractLifeCycle
    value: ERROR
  - name: log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper
    value: INFO
  - name: log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter
    value: INFO
  - name: log4j.logger.org.apache.parquet
    value: ERROR
  - name: log4j.logger.parquet
    value: ERROR
  - name: log4j.logger.org.apache.hadoop.hive.metastore.RetryingHMSHandler
    value: FATAL
  - name: log4j.logger.org.apache.hadoop.hive.ql.exec.FunctionRegistry
    value: ERROR
