---
- name: Ensure base user belongs to the docker group
  user:
    name: "{{ base_user_name }}"
    groups:
      - docker
- name: Create a tombstone container that prevents the default docker_gwbridge network to use 172.17.** subnet
# https://stackoverflow.com/questions/50514275/docker-bridge-conflicts-with-host-network
  docker_network:
    name: tombstone
    state: present
    force: yes
    ipam_config:
      - subnet: 172.17.253.0/30
- name: Initiate a new docker-swarm 
  docker_swarm:
    state: present
  register: swarm_facts

# - debug:
#     var: swarm_facts
#     var: swarm_facts.swarm_facts.JoinTokens.Worker
    # advertise_addr: If advertise_addr is not specified, it will be automatically detected when possible.


