---
- name: Initiate a new docker-swarm 
  docker_swarm:
    state: present
  # register: docker_swarm_facts
# - debug:
#     var: docker_swarm_facts
#     var: docker_swarm_facts.swarm_facts.JoinTokens
    # advertise_addr: If advertise_addr is not specified, it will be automatically detected when possible.


