---
- name: Ensure dependencies are installed
  apt:
    state: present
    name:
      - nfs-common
      - nfs-kernel-server
      - nginx
    install_recommends: true
    force_apt_get: true

- name: Disable NFS
  service:
    name: nfs-server
    enabled: no
    state: stopped

- name: Disable Nginx
  service:
    name: nginx
    enabled: no
    state: stopped

- name: Ensure Hail home directory exists
  file:
    state: directory
    path: "{{ hail_home }}"
    owner: "{{ hail_install_owner }}"
    group: "{{ hail_install_group }}"
    mode: "{{ hail_install_mode }}"
    follow: true

# - name: Ensure Hail source directory exist
#   file:
#     state: directory
#     path: "{{ hail_install_dir }}"
#
# - name: Ensure Hail git repo has been chacked out
#   git:
#     repo: "{{ hail_repo }}"
#     dest: "{{ hail_install_dir }}/hail"
#     update: no
#     version: "{{ hail_version }}"
#
# - name: Ensure gradlew is executable
#   file:
#     state: file
#     path: "{{ hail_install_dir }}/hail/hail/gradlew"
#     mode: "+x"
#
# - name: Build Hail
#   shell: "JAVA_HOME={{ java_home }} ./gradlew -Dspark.version={{ spark_version }} shadowJar"
#   args:
#     chdir: "{{ hail_install_dir }}/hail/hail"
#     creates: "{{ hail_install_dir }}/hail/hail/build/libs/hail-all-spark.jar"
#
# - name: Fix ownership on Hail installation
#   file:
#     path: "{{ hail_install_dir }}"
#     owner: "{{ hail_install_owner }}"
#     group: "{{ hail_install_group }}"
#     mode: "{{ hail_install_mode }}"
#     recurse: yes

- name: Configure system-wide environment variables
  template:
    src: profile.sh.j2
    dest: /etc/profile.d/40-hail.sh

- name: Ensure Derby database directory exists
  file:
    path: "{{ derby_home }}"
    state: directory
    owner: "{{ hail_install_owner }}"
    group: "{{ hail_install_group }}"
    mode: "{{ hail_install_mode }}"
