---
dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: ../../../yamllint.conf
platforms:
  - name: default
    image: eta-hgi-image-docker-base-0.1.2
    flavor: o2.medium
    role: console-base
provisioner:
  name: ansible
  options:
    extra-vars: "@../../../../molecule/default/metadata.yml,@../../../../vars/eta/hgi.yml"
  lint:
    name: ansible-lint
  playbooks:
    create: ../../../../molecule/default/create.yml
    destroy: ../../../../molecule/default/destroy.yml
    prepare: ../../../../molecule/default/prepare_image.yml
    converge: ../../../../molecule/default/converge.yml
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
#    - destroy
