---
anaconda_distribution: 2019.03-Linux-x86_64
anaconda_mirror: https://repo.anaconda.com/archive

anaconda_source_dir: "{{ base_source_dir }}"
anaconda_download_dir: "{{ base_download_dir }}"
anaconda_install_dir: "{{ base_user_home }}"

anaconda_install_owner: hgi
anaconda_install_group: informatics
anaconda_install_mode: u+rw,go+r
