---
- name: Wait for master NFS Server to come up
  wait_for:
    state: started
    host: spark-master
    port: 111
    delay: 10
    sleep: 5

- name: Mount Spark local directory
  mount:
    path: "{{ hail_home }}/tmp"
    state: mounted
    src: "spark-master:{{ hail_home }}/tmp"
    boot: no
    fstype: nfs4
