---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart spark-master
  become: yes
  systemd:
    name: spark-master
    state: restarted
    daemon_reload: yes
  listen: restart spark
