---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart spark-slave
  become: yes
  systemd:
    name: spark-slave
    state: restarted
    daemon_reload: yes
  listen: restart spark
